### ISSUE TITLE
Empty value on String field is not allowed

### ISSUE THREAD

**Issue by marko-ciric** [ryanfitz/vogels#42]
When defining a schema like: 
<pre>
var Item = vogels.define('Item', function (schema) {
    schema.UUID('id', {hashKey: true});
    schema.Number('asset_id').required();
    schema.Number('user_id').required();
    schema.String('asset');
</pre>
Calling
<pre>Item.create({id: 1, asset_id: 2, user_id: 3, asset: ''})</pre>
fails with 
<pre>details=[message=the value of asset is not allowed to be empty, path=asset, type=any.empty]</pre>

**Comment by marko-ciric** [comment]
@ryanfitz actually it fails for null values too.

**Comment by whiteboardmonk** [comment]
@marko-ciric

**Comment by RodH257** [comment]
I'm still having an issue with empty strings on nested properties, does this fix only work on the parent keys?

**Comment by set-killer** [comment]
Try with:

```
schema.String('asset').default("")
```

**Comment by RodH257** [comment]
I don't think that helps? The problem is that dynamodb doesn't accept empty strings, and vogels is only cleaning up empty strings at the top level of the object (ie it's not doing a deep search):
I think the core problem is that this omit, needs to be some sort of 'omit deep' (unfortunately lodash doesn't have that)
https://github.com/ryanfitz/vogels/commit/6fd7c2fbf7c47b3b20195fe7b89f9bbfae567d12#diff-50e3aa130a4f97a42ee2cf111c7b1d9dL10

I wonder if there's a way to make it happen at serialisation time rather than as a separate step
