### ISSUE TITLE
2.0.0 Release Notes

### ISSUE THREAD

**Issue by ryanfitz** [ryanfitz/vogels#50]
## Summary
**vogels** v2.0 introduces a new api for defining models. The new define api brings full JSON document support to **vogels**, including support for deeply nested documents.  DynamoDB Expression apis are exposed as options to all model methods. In order to support JSON documents the *update* api call has been switched to using UpdateExpressions from the deprecated AttributeUpdates api. The riskiest part of migrating to this version will be testing out your update operations.
 
* **Upgrade time**: low - a few hours to a day for most users
* **Complexity**: low - small list of well understood, easy to locate, and trivial to modify
* **Risk**: moderate - update item calls switched to using DynamoDB UpdateExpressions api
* **Dependencies**: moderate - requires using latest 2.1.x AWS-SDK and Joi 5.x.x.

## New Features
* Full JSON document support, including support for List, Map, and BOOL datatypes. Closes #16, #44
* New timestamps config option to automatically add the attributes **createdAt** and **updatedAt** when  defining a model. These attributes will get automatically get set when you create and update a record. 
* Flexible schema configuration to allow unknown, dynamic attributes both on top level and nested records
* Ability to fully configure global and local secondary indexes. Allows to configure index names, attribute projection settings and index throughput. Closes #43 , #48 
* adding deleteTable api to remove the table from DynamoDB. Closes #10  
* New integration test suite and integration with travis-ci. 
* 100% code coverage

## Bug Fixes
* CreateTables checks if error occurs while attempting to create a table. Fixes #41 
* Fixed error handling when streaming query, scan and parallel scan requests.
* Fixed retry handling when running query and scans. Fixes #45 

## Updated dependencies
* **Joi** to v5.1.0
* **aws-sdk** to v2.1.8 (Closes #49 )
* **async** to v0.9.0
* **lodash** to v3.1.0

### Define a Model
The api for defining a model has been changed to accept a block of json configuration. 

```javascript
var Joi = require('joi');

var Account = vogels.define('Account', {
  hashKey : 'email',

  // add the timestamp attributes (updatedAt, createdAt)
  timestamps : true,

  schema : {
    email   : Joi.string().email(),
    name    : Joi.string(),
    age     : Joi.number(),
    roles   : vogels.types.stringSet(),
    settings : {
      nickname      : Joi.string(),
      acceptedTerms : Joi.boolean().default(false)
    }
  }
});
```

### Secondary Indexes
Both local and global secondary indexes are defined when defining the model.

```javascript
var BlogPost = vogels.define('Account', {
  hashkey : 'email',
  rangekey : 'title',
  schema : {
    email             : Joi.string().email(),
    title             : Joi.string(),
    content           : Joi.binary(),
    PublishedDateTime : Joi.date()
  },

  indexes : [
    { hashkey : 'email', rangekey : 'PublishedDateTime', type : 'local', name : 'PublishedIndex' },
    { hashkey : 'title', rangekey : 'email', type : 'global', name : 'TitleEmailIndex' },
  ]
});
```

**Comment by keithchilders** [comment]
I like the new API. I'm not digging the need to require('Joi') in all your models for the types. I liked it better when you got back a schema object that contained all the types, or in the new API I think it would be better to have an alias to Joi types in vogels.types so all you need to require is vogels and the module dependency can bring in Joi unbeknownst to the user.

**Comment by keithchilders** [comment]
I will keep future commentary and feature requests for the new API in this issue rather than the pull request where we had been corresponding re: this release.

Thanks again for all your hard work on this, it's coming along beautifully!

**Comment by ryanfitz** [comment]
@keithchilders thanks for the feedback. I wrote a reply on the old pull request, but to consolidate things I'll reply here as well.

I do agree that its a bit awkward to always have to require Joi. One of the biggest problems I've run into with vogels is wrapping  / bundling Joi. The joi module moves extremely fast and its been difficult to keep up with their changes. One of the reasons why I needed to introduce a new define api is because Joi underwent a complete rewrite and I could no longer use it in the fashion that I was previously. One of my major goals with this release is to stop wrapping / extending Joi. I'm now following a more similar pattern to what the Joi developers do with hapi.js. 

The new api should allow developers to upgrade Joi at their own speed. This is what happens under the hapi framework and it has worked well for me in the past.  I'm hopeful that these api related to Joi will allow a nicer / quicker upgrade path for users.

I am open to ideas on how to improve the experience for users, without introducing the issues I've run into the past. Thanks again for the feedback

**Comment by keithchilders** [comment]
If I have to get Joi myself I will, but any chance you could just hang a static reference to the Joi you are bundling off the root of vogels so at least if I don't care to run cutting edge of Joi and just want to use the version you're using, I can get to it without requiring and packaging it myself, redundant with the dependency you've already brought in?

i.e. 

var vogels = require('vogels'),
      Joi = vogels.Joi;

I wouldn't call that "wrapping" per se; it's more of a convenience if it just passes through an instance of the Joi module raw for me to use.

**Comment by keithchilders** [comment]
Tell me more about how to define schema without chaining Joi methods together! That will make me happy :)

Here's some example psuedo dialect based on your previous API:

key: {type: 'String', required: true},
name: {type: 'String', required: true},
version: {type: 'Number', default:0},
date: {type: 'Date', default: new Date()}

All I had to do before was pass my string 'type' as your schema[type] method and invoke it. Now I have to know ahead of time whether stringSet() is a Joi type or or vogels.types type, and there are two sets of supported attributes per-type (default, required, etc.) I also don't love having to require Joi from outside my model; I'd much rather use it at the dependency level you specify in the vogels version I'm using, plus if the models are vogels models it seems like the vogels package should contain everything they need to instantiate them, so at least something like vogels.Joi as a reference to your dependency that I could bring in rather than a separate require of Joi at a version that may or may not be compatible would be preferable from my perspective.

**Comment by ryanfitz** [comment]
@keithchilders response to your pseudo dialect:

You actually can [compile](https://github.com/hapijs/joi#compileschema) a raw json object to a Joi schema, which in theory should work in your case. 

One thing also to note is even the custom vogels.types it is 100% joi definitions and are provided to offer a few shorthands around Sets and UUIDs. For example, here is how a string set is defined: Joi.array().includes(Joi.string()).meta({dynamoType : 'SS'});

I actually originally wanted to expose an api similar to your psuedo dialect, unfortunately with the introduction of nested attributes and in the way they work with DynamoDB I found it either too restrictive or too complicated for users to properly setup their models. You might run into a similar issue if you start using nested Maps & Lists.

**Comment by keithchilders** [comment]
Gotcha. That compile feature will work nicely for me. Since I was already using vogels via middleware where I added in related models, extend base model configuration and auto-discovery and initialization of all models in a folder, this won't be a big hit for me. I'll just package Joi with that middleware.

I still don't completely understand the reluctance to just let vogels.types.string be a straight passthrough to Joi.string at whatever version of Joi you've bundled, but hey, it's your project :)

**Comment by ryanfitz** [comment]
I pushed out version 2.0.0-rc1 to npm

**Comment by keithchilders** [comment]
Thanks!

**Comment by keithchilders** [comment]
Doesn't look like compile is going to be a solution for describing the schema in JSON. Seems like someone else tried this and one of the Joi devs responded less than favorably to the notion:

https://github.com/hapijs/joi/issues/423

Is there any chance you would be willing to let the schemas be described in pure JSON as they could be before 2.0 and handle the compilation of that back to Joi? I get that you want to decouple, but for all intents and purposes with this change you're just shifting the burden of dealing with data typing and validation onto the user. I strongly prefer to be able to describe my schemas in JSON rather than javascript code. I'm not sure if I'm in the majority or not; just offering my feedback as an end user. Plus, you're already bundling Joi at a specific dependency level for the StringSet, Map, etc. types and I still don't see (purely from my own perspective, notwithstanding all the problems you've had with this in the past) the value of being able to use a newer Joi library for string, number, boolean types while being tied to your bundled version for everything else.

Hope I'm not coming across as pushy or overly opinionated on this; just trying to help.

**Comment by keithchilders** [comment]
Could you point me at an example for using the new Map and List types? Do you just define a schema key as Joi.object() or Joi.array() type and start adding substructures to it?

I'm resigned to using code-based schemas--just need to figure out how to do it for all supported types.

**Comment by keithchilders** [comment]
@ryanfitz can I just bypass your vogels.types.stringSet() entirely and use the Joi.array() mapping to DynamoDB List type so I'll never have to deal with any types other than Joi types? Can you think of any drawbacks with that approach?

**Comment by keithchilders** [comment]
@ryanfitz with the new API do you have any ideas on how I might be able to chain additional queries into the get, query and scan methods that return models? Let's say I have related models in other tables and I want to load them non-lazy, so that when I run Model.get({id:123}) I can hook a subquery to go out and get the related records and expose them via instance methods in the returned model. I have already been able to create class and instance methods inside the model that can run those queries asynchronously for lazy loading but sometimes it's good to get back collections of related items along with the base item.

If this isn't the appropriate forum for asking usage questions re: the 2.0 api changes, please let me know where you'd like users to do so.

**Comment by keithchilders** [comment]
@ryanfitz Also per your last message, I dug into the code you linked and noticed that there's not an explicit mapping for the M dynamoType to Joi.object() in internals.wireType. Could that be why all my attempts to write object data to schema attr keys configured as such:

params: Joi.object().keys({
  name: Joi.string(),
  value: Joi.string()
});

result in a null value written to the corresponding dynamo attribute? Is Map not fully implemented yet in rc1? Arrays and arrays of objects seem to be working fine being mapped to dynamoType L and persisted as expected.

**Comment by ryanfitz** [comment]
@keithchilders Map should be fully working, check out [this example](https://github.com/ryanfitz/vogels/blob/document-support/examples/nestedAttributes.js) on how to create and update maps and lists.  I be working on the README soon to give better explanations on how to use nested attributes.

```javascript
Movie.create({
    title : 'Star Wars: Episode IV - A New Hope',
    releaseYear : 1977,
    director : {
      firstName : 'George', lastName : 'Lucas', titles : ['Director']
    },
    actors : [
      { firstName : 'Mark',     lastName : 'Hamill', titles : ['Actor']},
      { firstName : 'Harrison', lastName : 'Ford',   titles : ['Actor', 'Producer']},
      { firstName : 'Carrie',   lastName : 'Fisher', titles : ['Actress', 'Writer']},
    ],
    tags : ['Action', 'Adventure']
  }, printResults);

```

**Comment by keithchilders** [comment]
@ryanfitz That's strange, I did follow the example in nestedAttributes.js, and even simplified it a bit as above, but it doesn't seem to be working.

Is it not possible to define a schema element as simply:
...
key: Joi.object()
...
and not specify any keys, i.e. it will accept any keys you put in there? Do I have to define all the object keys with Joi.object().keys()?

Also any thoughts on chaining queries to get related items in a single get() or query()? Can I tap into your before or after constructs on the model class to hook other actions before the callback on the base method is invoked?

**Comment by keithchilders** [comment]
It looks like serializer.js:164 is expecting each attribute given as an object key to also be named in  Joi.object().keys() for map types. In Joi documentation for object(), a null or undefined schema passed to keys() (or keys() omitted entirely) is a valid case, meaning all keys allowed.

Should I report this as a bug or is this behavior as intended? If the latter, I'm not sure how schema being optional and/or unknown attributes allowed would work with Map since there wouldn't be a key spec for serializer to match object keys to.

**Comment by ryanfitz** [comment]
That was definitely a bug, thanks for finding it. I pushed up a fix and added a few integration tests to catch this in the future. I also added an [example](https://github.com/ryanfitz/vogels/blob/document-support/examples/dynamicKeys.js) to show how to use dynamic keys.

I pushed out 2.0.0-rc3, this should include this bug fix.

**Comment by keithchilders** [comment]
@ryanfitz Fantastic, thank you!

Any thoughts on my other inquiry (copied below)?

With the new API do you have any ideas on how I might be able to chain additional queries into the get, query and scan methods that return models? Let's say I have related models in other tables and I want to load them non-lazy, so that when I run Model.get({id:123}) I can hook a subquery to go out and get the related records and expose them via instance methods in the returned model. I have already been able to create class and instance methods inside the model that can run those queries asynchronously for lazy loading but sometimes it's good to get back collections of related items along with the base item.

If this isn't the appropriate forum for asking usage questions re: the 2.0 api changes, please let me know where you'd like users to do so.

**Comment by keithchilders** [comment]
In rc3 there appears to be a bug in the model instance update() method when there are attributes whose names begin with the _ character.

```
{ [ValidationException: Invalid UpdateExpression: Syntax error; token: "_", near: "SET _region"]
  message: 'Invalid UpdateExpression: Syntax error; token: "_", near: "SET _region"',
  code: 'ValidationException',
  time: Thu Jan 08 2015 11:24:17 GMT-0800 (Pacific Standard Time),
  statusCode: 400,
  retryable: false,
  retryDelay: 0 }
```

I was able to create() this model with the class method with _ prefixed attributes, but when I attempted to update it using the instance method with or without setting any values, I got this error. Maybe the UpdateExpression needs special characters escaped?

**Comment by keithchilders** [comment]
Another bug with the instance.update() api:

```
{ [ValidationException: Invalid UpdateExpression: Attribute name is a reserved keyword; reserved keyword: name]
  message: 'Invalid UpdateExpression: Attribute name is a reserved keyword; reserved keyword: name',
  code: 'ValidationException',
  time: Thu Jan 08 2015 11:45:27 GMT-0800 (Pacific Standard Time),
  statusCode: 400,
  retryable: false,
  retryDelay: 0 }
```

Apparently switching to UpdateExpression has had some input validation consequences that were not present before. In this case I'm trying to update() a model instance that has an attribute 'name'. Worked fine before, but seems like it's a reserved word in an expression. Maybe it needs to be quoted or escaped somehow too?

**Comment by ryanfitz** [comment]
@keithchilders You're running into a major pain point that amazon introduced with [Reserved Words](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ReservedWords.html) . Amazon added these new reserved words about a month ago when they launched document support. I've been in contact with people at AWS to express my concerns with them. There is nothing I can do to work around this, its a validation that DynamoDB enforces server side. One options I'm considering is to validate defined schemas to throw an error / warning if an attribute matches one of these new reserved words.

These reserved words are a major issues that AWS has introduced. If you want, I would email AWS to let them know the issues you're running into. Unfortunately in order to support nested records, vogels needs to switch to the expressions based apis.

**Comment by keithchilders** [comment]
No problem. Thanks for letting me know. I will contact AWS.

Very strange that they'll allow the attribute to be created with the reserved words present but they won't allow it to be subsequently updated through expressions. I guess they had to do that to not break existing datasets.

+1 for giving the friendly warning to the end user at ingest schema time, as this is some very low level AWS stuff that people are likely to dismiss as a flaw in your module rather than with the AWS expressions API upstream.

Now I understand why name is breaking, but why would anything starting with _ be broken too?

**Comment by deedw** [comment]
I think there is a way of escaping the reserved words in expressions:

http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.AccessingItemAttributes.html#ExpressionAttributeNames

**Comment by ryanfitz** [comment]
@deedw that is a great find, thanks. I was under the impression that these attribute names were completely black listed. 

I pushed up an update to using attributeNames when updating an item. Seems to be working well, after I do a bit more testing I'll release a new RC version

**Comment by keithchilders** [comment]
I just got off a call with the dynamodb team and they offered the following workaround based on the Java API but it should be applicable to node and raw as well:

```
 Map<String, AttributeValue> item = new HashMap<String, AttributeValue>();
            item.put(HASH_KEY_ATTRIBUTE, new AttributeValue().withN(hashIndex));
            item.put(RANGE_KEY_ATTRIBUTE, new AttributeValue().withN(rangeIndex));
            item.put("FOR", new AttributeValue().withS("FOR_ReservedKeyWord"));
            item.put("In", new AttributeValue().withS("In_ReservedKeyWord"));
            item.put("_system", new AttributeValue().withS("_System_ReservedKeyWord"));
            item.put("Normal", new AttributeValue().withS("Normal_AttributeName"));


==Get reserved keyword attributeNames from Item ===

            Map<String, String> expressionAttributeNames = Maps.newHashMap();
            expressionAttributeNames.put("#a", "FOR");
            expressionAttributeNames.put("#in", "In");
            expressionAttributeNames.put("#system", "_system");

            GetItemRequest itemRequest = new GetItemRequest()
                    .withTableName(tableName)
                    .withKey(key)
                    .withProjectionExpression(“#a, #in, #system, Normal")
                    .withExpressionAttributeNames(expressionAttributeNames)
                    ;
```

They recommend prefixing all attribute names with # in the expression (_ is in fact blacklisted and breaks the expression syntax) and using ExpressionAttributeNames to provide a mapping of #attributeName to attributeName. As long as there are no special characters in the attribute name itself, it should work.

**Comment by ryanfitz** [comment]
@keithchilders check out the latest rc version I pushed out (2.0.0-rc4). I'm now doing something very similar to what the AWS guys told you about. So far in my testing it is working well and gets around all of the reserved word issues we have been running into.

**Comment by keithchilders** [comment]
@ryanfitz Yeah I agree the fix definitely needs to be implemented in the query and scan APIs as well as update. If getItems becomes a problem I can either use query instead or pass in the expressionattributenames myself, as you recommend. 

It would be best for vogels to magically deal with as much of the AWS silliness as possible. The entire value proposition of the module from my point of view is making DynamoDB's somewhat unapproachable API a bit more tenable for developers from the javascript world who aren't used to working with strong types and wire serialization beyond JSON.

**Comment by keithchilders** [comment]
@ryanfitz any advice on hooking subqueries to other tables into get(), query(), scan(), etc. as per my previous inquiries?

**Comment by ryanfitz** [comment]
@keithchilders subqueries would be beyond the scope of this lib. Loading up related models is something you would see in an ORM, but its important to point out that DynamoDB is a key value store and not a relational database so its smart to not structure your database as such.

**Comment by keithchilders** [comment]
@ryanfitz Sure, I understand that, but even the dynamodb example applications published by AWS show the use of related tables for users and posts for example. If there's no way to hook a related subquery from within the model that's fine; it's easy enough to do it from outside.

**Comment by keithchilders** [comment]
@ryanfitz the destroy() API also needs the new ExpressionAttributeValues escaping. Whenever I do a destroy() in RC4, with or without reserved keywords in the expression, I get the following error:

"ValidationException: ExpressionAttributeValues must not be empty"

**Comment by keithchilders** [comment]
@ryanfitz seems that this same error occurs in the update api as well when you try to set an attribute value to null. There must be some bug in synthesized REMOVE expressions?

**Comment by ryanfitz** [comment]
@keithchilders can you post an example of the update and destroy operations that you are running? I just ran a test updating an attribute to null and it worked without issue.

**Comment by ryanfitz** [comment]
@keithchilders can you also post an example subqueries api that would meet your needs? I'm not sure I'm entirely following you on it.

**Comment by keithchilders** [comment]
@ryanfitz here's some example code that is breaking in node 0.10.31 on windows:

```
Test.create({rid:'12345',rng:'54321',foo:'bar'});

Test.get({rid:'12345',rng:'54321'},function(err,test){
   test.set({foo:null});
   test.update();
});

Test.update({rid:'12345',rng:'54321',foo:null});

Test.destroy({rid:'12345',rng:'54321'});

```

All three cases produce the aforementioned "ExpressionAttributeValues must not be empty" error.

Test model is defined with the following schema:

```
{
    rid: Joi.string(),
    rng: Joi.string(),
    foo: Joi.string()        
}

```

id is the hash key, rng is range key. I haven't tested it with models having only hash keys and no range.

**Comment by keithchilders** [comment]
@ryanfitz As regards subqueries, I have already set up instance methods on my models that will go out and grab related records. I am injecting them automatically by parsing my model pseudo-code as such:

```
model User:
{
  hashKey: 'id',
  schema: {
    id: vogels.types.uuid(),
    orders: vogels.types.stringSet()
  }
}

model Order:
{
  hashKey: 'id',
  schema: {
    id: vogels.types.uuid(),
    user: Joi.string()
  }
}    
```

In this case I'd store the id attribute from each related order in the Users model instance 'orders' set, then use Order.getItems() to query the orders back out by their keys rather than scanning the whole Order table looking for a user id that matched or building global secondary indexes on that attribute.

Right now when I create my models I inject getters for the related data into Model.prototype. This works fine for lazy loading, but sometimes I want to make a single query and get back related model instances already attached in a substructure that lets me interact with them against the other model's API.

So basically, I have lazy loading solved, but I need a solution similar to how you roll up multiple queries into a single response to get around dynamo's max records in a resultset restriction, except for attaching results from a subquery to another table rather than aggregating results for multiple queries on the same table.

**Comment by MixMasterMitch** [comment]
Going back to the comment by @keithchilders about having to require Joi in version 2.0.0, I would really prefer not to have to manage Joi directly as a user. My first choice of API would be as @keithchilders suggested:
```
schema: {
    key: {type: 'String', required: true},
    name: {type: 'String', required: true},
    version: {type: 'Number', default:0},
    date: {type: 'Date', default: new Date()}
}
```

My second choice would be to have Joi wrapped in voqels.types:
```
schema: {
    key: vogels.types.string().required(),
    name: vogels.types.string().required(),
    version: vogels.types.number().default(0),
    date: vogels.types.date().default(new Date())
}
```

Disclaimer: I am not currently a vogels user, but I am considering it due to the features in version 2.0.0.

**Comment by ryanfitz** [comment]
@MixMasterMitch thanks for the feedback. Question I have for your first choice, how would you declare a schema for nested documents?

**Comment by ryanfitz** [comment]
@keithchilders thanks for the example of the bug you were running into. I just pushed up a fix for it.

**Comment by MixMasterMitch** [comment]
@ryanfitz Hmm.... I didn't consider that. But something like this would be good:
```
schema: {
    key: {type: 'String', required: true},
    name: {type: 'String', required: true},
    version: {type: 'Number', default:0},
    date: {type: 'Date', default: new Date()}
    someNestedObject: {type: 'Object', schema: {
        key: {type: 'String', required: true},
        name: {type: 'String', required: true}
    }
}
```

**Comment by MixMasterMitch** [comment]
On a related note, is there a way to specify a secondary index on a nested key/value? I realize this may be a limitation of DynamoDB.

**Comment by ryanfitz** [comment]
@MixMasterMitch here is how you would declare that using joi, personally I find the joi way of declaring a schema to be easier to read and less to type. As I had mentioned to Keith previously, I would be willing to look into using a different validation library. If you could find one that is arguably better than Joi I would consider switching.

```js
schema : {
  key     : Joi.string().required(),
  name    : Joi.string().required(),
  version : Joi.number().default(0),
  date    : Joi.date().default(Date.now),
  someNestedObject : {
    key  : Joi.string().required(),
    name : Joi.string().required()
  }
}
```

DynamoDB does not a way to create an index on a nested key/value. Vogels doesn't currently offer any kind of convenience work arounds for this.  One solution is you copy a nested key and save it at the top level and declare an index on that top level key. This should be fairly easy to implement using *before* hooks. If you want, open up an issue for a feature that can copy nested attributes to a top level attribute. I could see it being a useful feature for certain circumstances

**Comment by keithchilders** [comment]
@MixMasterMitch I would like to see vogels support that kind of pure JSON schema definition as well, but I totally understand where @ryanfitz is coming from when he talks about the issues with staying current on a fast-moving dependency. As a compromise, I would propose a types library that I can pass into the model the same as I could pass schema before.

The biggest problem I'm having with the new model api vs. the old is having to know whether a stringSet or UUID type is Joi. or vogels.types.

I would prefer that vogels.types just include reflected Joi classes of the same name at minimum. If anyone doesn't want to be confined to that, they can opt to require Joi themselves and set the types that way. I just think that the vogels package should include everything you need to cast your attributes to the correct types, regardless of whether it supports JSON dialects for describing models.

**Comment by keithchilders** [comment]
@ryanfitz Thanks for the fix!

**Comment by ryanfitz** [comment]
@keithchilders This thread is getting a bit long. I don't want to lose track of the subqueries feature you were talking about before. Can you create a separate issue detailing that feature out a bit? It won't be something I can get in with the first 2.0 release, but can take a look once 2.0 gets out and all the bugs are worked out

**Comment by MixMasterMitch** [comment]
Having the Joi type functions reflected in the vogels.types object is a great solution to me.

**Comment by keithchilders** [comment]
@ryanfitz no problem, will open new issue for each discrete function or bug report from now on

Thanks!
