### ISSUE TITLE
Add support for add/drop indexes from live table

### ISSUE THREAD

**Issue by keithchilders** [ryanfitz/vogels#56]
AWS announced a new feature today that allows you to create or drop global secondary indexes on a table without having to delete and recreate the table. Vogels should support this feature in updateTable()

**Comment by justhamade** [comment]
Create is now implemented so this issue can probably be updated to just support deleting indexes.

**Comment by ryanfitz** [comment]
thanks @justhamade, I didn't see that this didn't get closed. 

For anyone looking at this, adding secondary indexes is now supported. If you call the `createTables` api, if the table is live any new declared indexes will get added.

It does not support dropping indexes, this is by design. Vogels attempts to be as safe as possible when dealing with deleting of data.

**Comment by justhamade** [comment]
@ryanfitz With the limit of indexes at 5 would it be possible to add a way to explicitly say you wanted to delete the ones that are no longer in the configuration.
