### ISSUE TITLE
why lodash over lazy.js

### ISSUE THREAD

**Issue by doapp-ryanp** [ryanfitz/vogels#59]
@ryanfitz - curious, why did you pick lodash over [lazy.js](https://github.com/dtao/lazy.js) for internals?  We really like vogels and would like to start using it in some of our products (and contributing back).  However we are still in our evaluation phase on what data mapper to use.  In practice we have seen lazy.js be [faster](http://danieltao.com/lazy.js/comparisons.html) in most comparisions.  Just curious on your thought process. thanks in advance.

**Comment by ryanfitz** [comment]
@doapp-ryanp I've been using underscore and then lodash for many years, its being used because its what I'm most productive in. 

I wouldn't be too concerned with the performance differences. Little work is performed with lodash and the performance hit making http requests will be several orders of magnitude greater calls to these libs.
