### ISSUE TITLE
UpdateTable does not support adding changing indexes / better migration support

### ISSUE THREAD

**Issue by addisonj** [ryanfitz/vogels#72]
Looking at the code, it doesn't seem that vogels deals with changing indexes (creating, deleting or updating), unless I am missing something? 

Is this something that seems in scope of the project? Support for looking at the current indexes on the table and the computing the changes would be pretty awesome. Perhaps some hooks to help with using something like https://github.com/tj/node-migrate?

I may see if I have some time to add a PR in the next few weeks, but wanted to see if you had any thoughts.

**Comment by ryanfitz** [comment]
This is definitely a feature Id like to add. Currently, vogels only creates indexes when its also creating the table. Adding indexes to existing tables is something I'd like to add shortly, send a PR if you get a chance. 

 I would probably not add in an auto delete index feature. I would hate it if someone accidentally blew out  a production table index because they had a typo in their vogels schema.

**Comment by justhamade** [comment]
I started pull request https://github.com/ryanfitz/vogels/pull/82 with my naive first attempt at this.  It works but it is ugly and would appreciate any feedback.

**Comment by focusaurus** [comment]
+1 I could use this as well. Good start, @justhamade

**Comment by ryanfitz** [comment]
I have an update ready to support this, but I've found a bug in the DynamoDB service itself regarding adding indexes to existing tables. I'm waiting to hear back from AWS before adding in this feature.
